name: aec_medical_doctor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  flutter_bounce: any
  delayed_display: any
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1
  animated_splash_screen: ^1.1.0
  image_picker:
  image_cropper:
  flutter_svg: ^0.23.0+1
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  provider: ^6.0.0
  share: ^2.0.4
  razorpay_flutter: ^1.2.3
  fluttertoast: ^8.0.2
  table_calendar: any
  expandable: ^5.0.1
  http: ^0.13.3
  flutter_slidable: ^0.6.0
  file_picker: ^3.0.3
  date_field: any
  firebase_messaging:
  url_launcher:
  email_validator: ^2.0.1
  syncfusion_flutter_signaturepad: ^19.3.45
  flutter_easyloading: ^3.0.3
  flutter_html:
  flutter_math_fork: ^0.5.0
  jitsi_meet: ^4.0.0
  flutter_countdown_timer: ^4.1.0
  photo_view: ^0.13.0
  google_fonts: ^2.2.0
  empty_widget: ^0.0.5
  math_expressions: ^1.1.0
  search_choices: ^2.0.16






dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/paymentimage.png
    - assets/images/dermotology.png
    - assets/images/audio_call.png
    - assets/images/video_call.png
    - assets/images/slider1.jpg
    - assets/images/slider2.jpg
    - assets/images/step1.png
    - assets/images/editprofile.png
    - assets/images/physician.png
    - assets/images/onboard1.png
    - assets/images/paymentsuccess.png
    - assets/images/register.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png
    - assets/images/googleicon.png
    - assets/images/drawer_icon.png
    - assets/images/shareapp_icon.png
    - assets/images/calendar_icon.png
    - assets/images/medical_icon.png
    - assets/images/profile_icon.png
    - assets/images/home.png
    - assets/images/my_consultation.png
    - assets/images/medical.png
    - assets/images/total_health.png
    - assets/images/online_consultation.png
    - assets/images/my_account.png
    - assets/images/my_course.png
    - assets/images/offers.png
    - assets/images/account_settings.png
    - assets/images/help.png
    - assets/images/share.png
    - assets/images/rate_us.png
    - assets/images/logout.png
    - assets/images/camera.png
    - assets/images/image.png
    - assets/images/upload.png
    - assets/images/medical_records.png
    - assets/images/healthcardimage1.png
    - assets/images/healthcardimage2.png
    - assets/images/intro.png
    - assets/fonts/otpverification.png
    - assets/images/motivationimage.jpg
    - assets/images/phonenumberverified.gif
    - assets/images/graduate.png
    - assets/images/hospital.png
    - assets/images/ribbon.png
    - assets/images/award.png
    - assets/images/money.png
    - assets/images/rupee.png
    - assets/images/calendar.png
    - assets/images/earning.png
    - assets/images/Earning.svg
    - assets/images/prescription.png
    - assets/images/nothinghere.png
    - assets/images/translate.png
    - assets/images/counselor.png
    - assets/images/template.png
    - assets/images/upcoming.svg
    - assets/images/Component.svg
    - assets/images/nonotification.jpg
    - assets/images/noprescription.jpg
    - assets/images/nohistory.jpeg
    - assets/images/noearning.jpg
    - assets/images/bookcounseling.png
    - assets/images/gender.png
    - assets/images/birthday.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
